### ISSUE TITLE
base_url not working

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-nhs-organisations#11]
Although calls directly to the azure webapp URL are working, the api should be behind the APIM and therefore accept calls to [`https://api.rcpch.ac.uk/nhs-organisations/v1/`](https://api.rcpch.ac.uk/nhs-organisations/v1/) the same as [https://rcpch-nhs-organisations.azurewebsites.net/](https://rcpch-nhs-organisations.azurewebsites.net/)
Currently this returns a 404, whereas the azure URL works

**Comment by mbarton** [comment]
I think this is because there is an Open API spec registered for that API which does not include a root endpoint ([internal forum link](https://forum.rcpch.tech/t/apim-urls-rcpch-nhs-organisations-access/116/2))
