### ISSUE TITLE
Paediatric Diabetes networks

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-nhs-organisations#29]
Currently PZ code relating to individual paediatric diabetes units are included in the Organisation model.

PDUs themselves though are part of wider regional paediatric diabetes networks. These need including and will be necessary for NPDA reporting. Any information we publish here we can pull into NPDA or might be useful in time for other things related to paediatric diabetes nationally.

To close:
- [x] @AmaniKrayemRCPCH to provide a list of all networks with their names. If any other information is helpful to retain in the API such as names of network leads/coordinators/contacts etc please include these. Note that these will be in the public domain if published here and will need maintenance as people move around. The work flow for this would be for the moment to post each of these changes here as individual issues and in time we can find a way to automate the process if this service is used a lot or this becomes too much work.
- [x] Allocate unique identifiers to each network - @AmaniKrayemRCPCH it would be good if, like PZ codes, whatever we do here might become an RCPCH standard
- [x] Create a `paediatric_diabetes_networks.py` file in constants and use this to seed a new model
- [x] Create a new `PaediatricDiabetesNetwork` class model and add a foreign key to the `Organisation` model
- [x] Add a seed function to seed the new table along the lines of: `python manage.py seed --model=seed__paediatric_diabetes_networks`
- [x] create a new endpoint to serve a list of all paediatric diabetes networks with nested organisations/paediatric diabetes units, that might accept the new network id for the detail view.
- [x] update the `/paediatric_diabetes_units/trust/` endpoint `/paediatric_diabetes_units/sibling-organisations/` endpoints to include the network uid and name in the return objects.

**Comment by AmaniKrayemRCPCH** [comment]
Attached is the list of PDUs and the lookup to trust, icb, network, region, and country. 
[NPDA Units_20240827.xlsx](https://github.com/user-attachments/files/16761731/NPDA.Units_20240827.xlsx)

**Comment by eatyourpeas** [comment]
Note the only item on this list that changes is the relationship with PaediatricDiabetesNetwork which is as a foreign key in PaediatricDiabetesUnit, not Organisation

**Comment by eatyourpeas** [comment]
For future reference, the refactored `paediatric_diabetes_units/parent` now returns and object structured like this:
```json
{
    "pz_code": "PZ002",
    "paediatric_diabetes_network": {
      "pn_code": "PN06",
      "name": "East of England"
    },
    "parent": {
      "ods_code": "RM1",
      "name": "NORFOLK AND NORWICH UNIVERSITY HOSPITALS NHS FOUNDATION TRUST",
      "address_line_1": "COLNEY LANE",
      "address_line_2": "COLNEY",
      "town": "NORWICH",
      "postcode": "NR4 7UY",
      "country": "ENGLAND",
      "telephone": null,
      "website": null,
      "active": true,
      "published_at": null
    },
    "primary_organisation": {
      "ods_code": "RM102",
      "name": "NORFOLK & NORWICH UNIVERSITY HOSPITAL"
    }
  },
```
The new unique identifiers for the Paediatric Diabetes Networks are:
| Network ID | Network Name |
|----|----|
| PN01| Jersey|
| PN02 | South West |
| PN03 | South Central |
| PN04 | Thames Valley |
| PN05 | London & South East |
| PN06 | East of England |
| PN07 | Wales |
| PN08 | West Midlands |
| PN09 | East Midlands |
| PN10 | Yorkshire & Humber |
| PN11 | North West |
| PN12 | North East & North Cumbria |
