### ISSUE TITLE
Deploy to Azure and put behind APIM

### ISSUE THREAD

**Issue by mbarton** [rcpch/rcpch-nhs-organisations#5]
Free to access, no key required.

We probably want to do https://github.com/rcpch/rcpch-nhs-organisations/issues/3 first to make it easier to deploy

**Comment by eatyourpeas** [comment]
In the end this now deployed - I went in the end for postgis as a managed service within azure and put it behind the APIM, but it is accessible at [https://rcpch-nhs-organisations.azurewebsites.net/](https://rcpch-nhs-organisations.azurewebsites.net/) or [https://api.rcpch.ac.uk/nhs-organisations/v1/](https://api.rcpch.ac.uk/nhs-organisations/v1/). This latter option the browsable API css seems not to work but it accepts requests.
<img width="442" alt="image" src="https://github.com/rcpch/rcpch-nhs-organisations/assets/1058647/9e141826-9e9e-4aae-9bc7-7527ca7e8ae2">
